core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('screener/<str:title>/<str:clause>', views.screener, name='screener'),
    path('pricing/', views.pricing, name='pricing'),
    path('pay/<int:price>', views.pay, name='pay'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('contact', views.contact, name='contact'),
    path('terms', views.terms, name='terms'),
	path('get_data/<str:title>/<str:clause>', views.get_data, name='get_data'),
    path('market_is_open/<str:date>', views.market_is_open, name="market_is_open"),
    #path('options/', views.options, name='options')
]

screener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from .managers import CustomUserManager
from django.conf import settings
from datetime import date, timedelta

# Create your models here.
class User(AbstractUser):
    email = models.EmailField("email address", unique=True)
    subscription_valid = models.DateField(default=(date.today() - timedelta(1))) 
    USERNAME_FIELD = "email" # make the user log in with the email
    REQUIRED_FIELDS = ["username"]

    objects = CustomUserManager()

    @property
    def subscribed(self):
        if (date.today() - self.subscription_valid) < timedelta(0):
            return True
        return False


class Transactions(models.Model):
    made_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='transactions')
    made_on = models.DateTimeField(auto_now_add=True)
    amount = models.IntegerField()
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True)
    checksum = models.CharField(max_length=100, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.order_id is None and self.made_on and self.id:
            self.order_id = self.made_on.strftime('PAY2ME%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)        

class Screener(models.Model):
    title = models.CharField(max_length=100)
    nifty_clause = models.CharField(max_length=1000, default='')
    future_clause = models.CharField(max_length=1000, default='')
    cash_clause = models.CharField(max_length=1000, default='')

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User

class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

    class Meta:
        model = User
        fields = ("username", "email", "password1") 

class LogInForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

core/views.py
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from datetime import date, timedelta, datetime, timezone
import pandas_market_calendars as mcal
from .forms import *
from .models import * 

def index(request):
    return render(request, 'core/index.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('core:index')
        else:
            print('invalid form')
    else:
        form = SignUpForm()   
    return render(request, 'core/signup.html', {'form': form})

def log_in(request):
    error = False
    if request.user.is_authenticated:
        return redirect('core:index')
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)  
                return redirect('core:index')
            else:
                error = True
    else:
        form = LogInForm()

    return render(request, 'core/login.html', {'form': form, 'error': error})


def log_out(request):
    logout(request)
    return redirect('core:login')


# data = {
#   'scan_clause': '( {cash} ( latest volume >= 100000 and latest close >= 100 and latest close >= latest ema( latest close , 20 ) and latest close >= latest close and latest "close - 1 candle ago close / 1 candle ago close * 100" <= 5 and ( latest high - latest close ) / ( latest high - latest low ) <= 0.5 and latest ema( latest close , 9 ) >= latest ema( latest close , 20 ) ) )'
# }

def pay(request, price):
    if price == 699:
        price = 699*3
    elif price == 499:
        price = 499*12

    return render(request, 'core/pay.html', {
        'price': price
    })

def screener(request, title, clause):
    if request.user.is_anonymous:
        return render(request, 'core/error.html')
    if not request.user.subscribed:
        return render(request, 'core/error.html')

    # list of clauses
    clauses = ['Cash', 'Nifty500', 'Future']
    # screeners
    screeners = Screener.objects.all().values('title', 'cash_clause', 'nifty_clause', 'future_clause')
    stocks = get_data(request, title, clause)

    print(clause)

    return render(request, 'core/screener.html', {
        'screeners': screeners,
        'stocks': stocks,
        'current_title': title,
        'current_clause': clause,
        'clauses': clauses,
    })

@csrf_exempt
def get_data(request, title, clause):    
    data = {}
    clause = f"{clause}_clause".lower()
    print(clause)
    if clause == 'nifty500_clause':
        clause = 'nifty_clause'

    with requests.Session() as s:
        data['scan_clause'] = Screener.objects.filter(title=title).values(clause)[0][clause]
        r = s.get('https://chartink.com/screener/')
        soup = bs(r.content, 'lxml')
        s.headers['X-CSRF-TOKEN'] = soup.select_one('[name=csrf-token]')['content']
        r = s.post('https://chartink.com/screener/process', data=data).json()
        stocks = dict(r) 
        stocks = sorted(r['data'], key=lambda x: x["per_chg"], reverse=True)

        if request.method == 'POST':
            return JsonResponse(stocks, safe=False)

        return stocks 
        
def pricing(request):
  return render(request, 'core/pricing.html')  

def contact(request):
    return render(request, 'core/contact.html')

def terms(request):
    return render(request, 'core/terms.html')

def options(request):
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36','Accept-Encoding': 'gzip, deflate, br','Accept-Language': 'en-US,en;q=0.9,hi;q=0.8'}
    url = "https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY"
    data = requests.get(url, headers = headers).json()  
    print(data['filtered'])
    return render(request, 'core/options.html', {
        'data': data['filtered'],
    })

def market_is_open(request, date):
    result = mcal.get_calendar("BSE").schedule(start_date=date, end_date=date)    
    status = result.empty == False
    hours = market_hours()
    response = {'status': status, 'hours': hours}
    return JsonResponse(response, safe=False)

def market_hours():
    tzinfo = timezone(timedelta(hours=5.50))
    start_now=datetime.now(tzinfo).replace(hour=9, minute=15, second=0, microsecond=0)
    end_now=datetime.now(tzinfo).replace(hour=15, minute=30, second=0, microsecond=0)
    
    now = datetime.now(tzinfo)
    return start_now<now<end_now

core/templates/core/error.html
<h1>ERROR 404</h1>

core/templates/core/login.html
{% extends 'core/layout.html' %}

{% block main %}
<form method="post">
{% csrf_token %}
<section class="bg-gray-50 dark:bg-gray-800">
<div class="flex flex-col items-center justify-center mx-auto md:h-screen lg:py-0">
  <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">    
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
	  <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
	     Login 
	  </h1>
	  <form class="space-y-4 md:space-y-6" action="#">
	    <ul>  
	    <div>
		  <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
		    {{form.email}} 
	      </div>
	      <div>
		  <label for="password" class="block mb-2 mt-1 text-sm font-medium text-gray-900 dark:text-white">Password</label>
		    {{form.password}}
		</div>
	    </ul>
		  <button type="submit" class="w-full text-white bg-cyan-600 hover:bg-cyan-500 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-cyan-600 dark:hover:bg-cyan-500 dark:focus:ring-primary-800">Login</button>
	      <p class="text-sm font-light text-gray-500 dark:text-gray-400">
		  Don't have an account? <a href="{% url 'core:signup' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Register here</a>
	      </p>
	  </form>
      </div>
  </div>
</div>
</section>
</form>

{% endblock %}

core/templates/core/options.html
{% extends 'core/layout.html' %}
{% load static %}
{% block style %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="{% static 'index.js'%}"></script>
{% endblock %}

{% block main %}
<div id="chart" style="width: 600px; margin: 40px auto"></div>

<script>
    var data = '{{data|escapejs}}'
    console.log('data')
    console.log(data)
</script>
{% endblock %}

core/templates/core/pay.html
{% extends 'core/layout.html' %}

{% block main %}
<main class="spce-y-40 mb-40">
<div class="max-w-7xl mx-auto px-6 md:px-12 xl:px-6">
<div class="relative pt-36 ml-auto">
        <div class="lg:w-2/3 mx-auto">
            <ul class="list-disc">
            <h2 class="text-gray-900 dark:text-white font-bold text-2xl md:text-3xl xl:text-4xl">Please follow these instructions to complete your transaction and gain access to the stock screener</h1>
            <br><br>
            <li class="text-gray-900 dark:text-white text-2xl md:text-3xl xl:text-4xl">1. Send ₹{{price}} to this UPI ID:<br><span class="text-primary dark:text-white font-bold">tradewithv1@pnb</span></li>
            <li class="mt-8 text-gray-900 text-2xl dark:text-white md:text-3xl xl:text-4xl">2. Send the screenshot of the payment and your email id you used to register on this website to <span class="font-bold">@trade.withv</span> on instagram.<br><br> We'll respond as quickly as possible</li>
            </ul>
        </div>
    </div>
</div>
</main>
{% endblock %}

core/templates/core/pricing.html
{% extends 'core/layout.html' %}

{% block main %}
<!-- bg-gradient-to-r from-gray-50 to-gray-100 dark:from-zinc-900 dark:to-zinc-800 -->
<main class="space-y-40 mb-40">
<section class="">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
    
      <div class="mx-auto max-w-screen-md text-center mb-8 lg:mb-12">
          <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Get full access to the screener</h2>
      </div>
      <div class="space-y-8 lg:grid lg:grid-cols-3 sm:gap-6 xl:gap-10 lg:space-y-0">
          <!-- Pricing Card -->
          <div class="flex flex-col p-6 mx-auto max-w-lg text-center text-gray-900 bg-white rounded-lg border border-gray-100 shadow dark:border-gray-600 xl:p-8 dark:bg-gray-800 dark:text-white">
              <h3 class="mb-4 text-2xl font-semibold">Starter</h3>
              <p class="font-light text-gray-500 sm:text-lg dark:text-gray-400">Best option for trying out.</p>
              <div class="justify-center items-baseline my-8">
                <span class="block text-gray-500 dark:text-gray-400">₹700/month</span>
                  <span class="mr-2 text-5xl font-extrabold">₹2099</span>
                  <span class="text-gray-500 dark:text-gray-400">/3month</span>
              </div>
              <!-- List -->
              <ul role="list" class="mb-8 space-y-4 text-left">
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Full Access To Screeners</span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>No setup, or hidden fees</span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Usage: <span class="font-semibold">3 month</span></span>
                  </li>
                  <li class="flex items-center space-x-3">
                    <!-- Icon -->
                    <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                    <span>Live Mentorship <span class="font-semibold">No</span></span>
                </li>
                <li class="flex items-center space-x-3">
                    <!-- Icon -->
                    <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                    <span>Free updates: <span class="font-semibold">Yes</span></span>
                </li>
              </ul>
              <a href="{% url 'core:pay' price=2099 %}" class="text-white bg-cyan-600 hover:bg-cyan-500 focus:ring-4 focus:ring-primary-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:text-white  dark:focus:ring-primary-900">Get 700*3mo Plan</a>
          </div>
          <!-- Pricing Card -->
          <div class="flex flex-col p-6 mx-auto max-w-lg text-center text-gray-900 bg-white rounded-lg border border-gray-100 shadow dark:border-gray-600 xl:p-8 dark:bg-gray-800 dark:text-white">
              <h3 class="mb-4 text-2xl font-semibold">Pro</h3>
	     <div class="px-1 py-1 text-md text-white bg-gradient-to-r from-pink-500 to-purple-500 rounded-full inline-block">
          	Most Worth It
       	     </div> 
	      <div class="justify-center items-baseline my-8">
                <span class="block text-gray-500 dark:text-gray-400">₹1399/month</span>
                  <span class="mr-2 text-5xl font-extrabold">₹4199</span>
                  <span class="text-gray-500 dark:text-gray-400">/3month</span>
              </div>
              <!-- List -->
              <ul role="list" class="mb-8 space-y-4 text-left">
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Full Access To Screeners</span>

                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Mentopship Program Worth ₹3499</span>
                  </li>
		  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>No setup, or hidden fees</span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Usage: <span class="font-semibold">3 Months</span></span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Live Mentorship: <span class="font-semibold">Yes</span></span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Free updates: <span class="font-semibold">Yes</span></span>
                  </li>
              </ul>
              <a href="{% url 'core:pay' price=4199 %}" class="text-white bg-cyan-600 hover:bg-cyan-500 focus:ring-4 focus:ring-primary-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:text-white  dark:focus:ring-primary-900">Get 1399*3 Plan</a>
          </div>
          <!-- Pricing Card -->
          <div class="flex flex-col p-6 mx-auto max-w-lg text-center text-gray-900 bg-white rounded-lg border border-gray-100 shadow dark:border-gray-600 xl:p-8 dark:bg-gray-800 dark:text-white">
              <h3 class="mb-4 text-2xl font-semibold">Ultimate</h3>
              <p class="font-light text-gray-500 sm:text-lg dark:text-gray-400">Best for committed traders</p>
              <div class=" justify-center items-baseline my-8">
                <span class="block text-gray-500 dark:text-gray-400">₹500*/month</span>
                  <span class="mr-2 text-5xl font-extrabold">₹5999</span>
                  <span class="text-gray-500 dark:text-gray-400">/year</span>
              </div>
              <!-- List -->
              <ul role="list" class="mb-8 space-y-4 text-left">
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Full Access To Screeners</span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>No setup, or hidden fees</span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Usage: <span class="font-semibold">12 months</span></span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Live Mentorship: <span class="font-semibold">Yes</span></span>
                  </li>
                  <li class="flex items-center space-x-3">
                      <!-- Icon -->
                      <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                      <span>Free updates: <span class="font-semibold">Yes</span></span>
                  </li>
              </ul>
              <a href="{% url 'core:pay' price=5999 %}" class="text-white bg-cyan-600 hover:bg-cyan-500 focus:ring-4 focus:ring-primary-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:text-white  dark:focus:ring-primary-900">Get 500*12 Plan</a>
          </div>
      </div>
  </div>
</section>
</main>
{% endblock %}